set -s set-clipboard on

set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-features ",xterm-256color:RGB"

set -as terminal-features ',xterm-256color:clipboard'
set -as terminal-overrides ',xterm*.256color:Ms=\E]52;c;%p2%s\7'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
